import { canonicalToken } from '@lib'
import {
  genreSchema,
  moodSchema,
  settingSchema,
  timeOfDaySchema,
  weatherSchema,
  archetypeSchema,
  buildSchema,
  voiceRegisterSchema,
  voiceRateSchema,
  entranceFromSchema,
  exitToSchema,
  movementStyleSchema,
  silhouetteAccentSchema,
  cameraMoveSchema,
  cameraIntensitySchema,
  lightingPresetSchema,
  lightingTransitionSchema,
  musicActionSchema,
  musicStingerSchema,
  particleEffectSchema,
  particleActionSchema,
  stageSlotSchema,
  facingSchema,
  travelStyleSchema,
  deliverySchema,
  gestureSchema,
  outroStyleSchema,
  beatSchema,
} from '../sceneScript.schema'

/**
 * A closed vocabulary plus the out-of-vocabulary values that map into it.
 *
 * `options` is always read from the live Zod enum, never re-typed, so a
 * schema change can't leave a stale copy behind. `aliases` keys are
 * canonical tokens (see `canonicalToken`) — casing, spacing, and
 * punctuation variants are matched before the table is consulted, so only
 * genuinely *different words* belong here.
 *
 * Every alias must be a true synonym, a strict subtype, or the nearest
 * renderable neighbour of its target. Arbitrary substitutions (lighthouse
 * to forest, mystery to drama) are what `fallback` is for, and `fallback`
 * is deliberately the least-committal member of each vocabulary.
 */
export interface Vocabulary<T extends string> {
  readonly options: readonly T[]
  readonly aliases: Readonly<Record<string, T>>
  /**
   * Used when nothing else matches. `undefined` means the value cannot be
   * guessed: the field is either dropped (when optional) or left in place
   * for Zod to reject (when required).
   */
  readonly fallback?: T
}

/** Beat `type` has no standalone Zod enum — it's the union's discriminator. */
const beatTypeOptions = beatSchema.options.map((option) => option.shape.type.value)

export const vocabularies = {
  genre: {
    options: genreSchema.options,
    aliases: {
      crime: 'noir',
      neonoir: 'noir',
      detective: 'mystery',
      whodunit: 'mystery',
      suspense: 'thriller',
      psychological: 'thriller',
      spy: 'thriller',
      espionage: 'thriller',
      survival: 'thriller',
      sciencefiction: 'scifi',
      dystopian: 'scifi',
      cyberpunk: 'scifi',
      spaceopera: 'scifi',
      paranormal: 'supernatural',
      occult: 'supernatural',
      ghoststory: 'supernatural',
      gothic: 'horror',
      slasher: 'horror',
      romanticcomedy: 'romance',
      romcom: 'romance',
      satire: 'comedy',
      darkcomedy: 'comedy',
      war: 'action',
      superhero: 'action',
      disaster: 'action',
      epic: 'adventure',
      quest: 'adventure',
      fairytale: 'fantasy',
      magicrealism: 'fantasy',
      mythology: 'fantasy',
      caper: 'heist',
      robbery: 'heist',
      wildwest: 'western',
      historical: 'drama',
      period: 'drama',
      biopic: 'drama',
      tragedy: 'drama',
      family: 'drama',
      comingofage: 'drama',
    },
    fallback: 'drama',
  },

  mood: {
    options: moodSchema.options,
    aliases: {
      dark: 'ominous',
      eerie: 'ominous',
      foreboding: 'ominous',
      dread: 'ominous',
      sinister: 'ominous',
      unsettling: 'ominous',
      creepy: 'ominous',
      menacing: 'ominous',
      anxious: 'tense',
      nervous: 'tense',
      suspenseful: 'tense',
      uneasy: 'tense',
      sad: 'melancholy',
      somber: 'melancholy',
      sombre: 'melancholy',
      mournful: 'melancholy',
      wistful: 'melancholy',
      lonely: 'melancholy',
      bleak: 'melancholy',
      bittersweet: 'melancholy',
      reflective: 'melancholy',
      contemplative: 'melancholy',
      whimsical: 'playful',
      lighthearted: 'playful',
      comedic: 'playful',
      funny: 'playful',
      wry: 'playful',
      victorious: 'triumphant',
      heroic: 'triumphant',
      exultant: 'triumphant',
      defiant: 'triumphant',
      enigmatic: 'mysterious',
      cryptic: 'mysterious',
      curious: 'mysterious',
      surreal: 'mysterious',
      chaotic: 'frantic',
      panicked: 'frantic',
      urgent: 'frantic',
      manic: 'frantic',
      desperate: 'frantic',
      warm: 'tender',
      intimate: 'tender',
      gentle: 'tender',
      romantic: 'tender',
      optimistic: 'hopeful',
      uplifting: 'hopeful',
      encouraging: 'hopeful',
      yearning: 'hopeful',
    },
    fallback: 'tense',
  },

  setting: {
    options: settingSchema.options,
    aliases: {
      kitchen: 'diner',
      restaurant: 'diner',
      cafe: 'diner',
      coffeeshop: 'diner',
      bar: 'diner',
      saloon: 'diner',
      pub: 'diner',
      tavern: 'diner',
      bookshop: 'library',
      bookstore: 'library',
      archive: 'library',
      study: 'library',
      museum: 'library',
      street: 'alley',
      backalley: 'alley',
      sidewalk: 'alley',
      courtyard: 'alley',
      spacestation: 'spaceship',
      starship: 'spaceship',
      shuttle: 'spaceship',
      airlock: 'spaceship',
      cockpit: 'spaceship',
      space: 'spaceship',
      woods: 'forest',
      jungle: 'forest',
      grove: 'forest',
      swamp: 'forest',
      park: 'forest',
      garden: 'forest',
      roof: 'rooftop',
      terrace: 'rooftop',
      balcony: 'rooftop',
      ledge: 'rooftop',
      factory: 'warehouse',
      garage: 'warehouse',
      hangar: 'warehouse',
      workshop: 'warehouse',
      storage: 'warehouse',
      basement: 'warehouse',
      cellar: 'warehouse',
      bunker: 'warehouse',
      vault: 'warehouse',
      barn: 'warehouse',
      prison: 'warehouse',
      bank: 'office',
      courtroom: 'office',
      precinct: 'office',
      policestation: 'office',
      interrogationroom: 'office',
      boardroom: 'office',
      newsroom: 'office',
      classroom: 'office',
      school: 'office',
      wasteland: 'desert',
      canyon: 'desert',
      dunes: 'desert',
      badlands: 'desert',
      bedroom: 'apartment',
      livingroom: 'apartment',
      house: 'apartment',
      home: 'apartment',
      flat: 'apartment',
      hotel: 'apartment',
      hotelroom: 'apartment',
      motel: 'apartment',
      penthouse: 'apartment',
      attic: 'apartment',
      train: 'subway',
      trainstation: 'subway',
      platform: 'subway',
      tunnel: 'subway',
      metro: 'subway',
      underground: 'subway',
      sewer: 'subway',
      cave: 'subway',
      mine: 'subway',
      catacombs: 'subway',
      abstract: 'void',
      nowhere: 'void',
      dream: 'void',
      limbo: 'void',
      darkness: 'void',
      beacon: 'lighthouse',
      pier: 'lighthouse',
      harbor: 'lighthouse',
      harbour: 'lighthouse',
      wharf: 'lighthouse',
      coast: 'lighthouse',
      shore: 'lighthouse',
      beach: 'lighthouse',
      dock: 'lighthouse',
      boat: 'ship',
      submarine: 'ship',
      deck: 'ship',
      ferry: 'ship',
      yacht: 'ship',
      vessel: 'ship',
      freighter: 'ship',
      ocean: 'ship',
      sea: 'ship',
      clinic: 'hospital',
      morgue: 'hospital',
      asylum: 'hospital',
      ward: 'hospital',
      operatingroom: 'hospital',
      emergencyroom: 'hospital',
      infirmary: 'hospital',
      sanatorium: 'hospital',
      cathedral: 'church',
      chapel: 'church',
      temple: 'church',
      monastery: 'church',
      shrine: 'church',
      confessional: 'church',
      abbey: 'church',
      mosque: 'church',
      synagogue: 'church',
      lab: 'laboratory',
      researchlab: 'laboratory',
      facility: 'laboratory',
      cleanroom: 'laboratory',
      observatory: 'laboratory',
      cemetery: 'graveyard',
      crypt: 'graveyard',
      tomb: 'graveyard',
      mausoleum: 'graveyard',
      burialground: 'graveyard',
      churchyard: 'graveyard',
      cottage: 'cabin',
      lodge: 'cabin',
      hut: 'cabin',
      shack: 'cabin',
      farmhouse: 'cabin',
      campsite: 'cabin',
      road: 'highway',
      freeway: 'highway',
      motorway: 'highway',
      interstate: 'highway',
      parkinglot: 'highway',
      gasstation: 'highway',
      car: 'highway',
      truckstop: 'highway',
      crossroads: 'highway',
      bridge: 'highway',
      mountains: 'mountain',
      peak: 'mountain',
      summit: 'mountain',
      cliff: 'mountain',
      glacier: 'mountain',
      tundra: 'mountain',
      arctic: 'mountain',
      snowfield: 'mountain',
      ridge: 'mountain',
      valley: 'mountain',
      fortress: 'castle',
      palace: 'castle',
      keep: 'castle',
      citadel: 'castle',
      manor: 'castle',
      mansion: 'castle',
      throneroom: 'castle',
      dungeon: 'castle',
      ruins: 'castle',
      tower: 'castle',
    },
    fallback: 'void',
  },

  timeOfDay: {
    options: timeOfDaySchema.options,
    aliases: {
      morning: 'dawn',
      sunrise: 'dawn',
      daybreak: 'dawn',
      predawn: 'night',
      afternoon: 'day',
      noon: 'day',
      midday: 'day',
      daytime: 'day',
      evening: 'dusk',
      sunset: 'dusk',
      twilight: 'dusk',
      gloaming: 'dusk',
      midnight: 'night',
      nighttime: 'night',
      latenight: 'night',
    },
    fallback: 'night',
  },

  weather: {
    options: weatherSchema.options,
    aliases: {
      mist: 'fog',
      haze: 'fog',
      smog: 'fog',
      foggy: 'fog',
      drizzle: 'rain',
      downpour: 'rain',
      rainy: 'rain',
      shower: 'rain',
      blizzard: 'snow',
      snowy: 'snow',
      sleet: 'snow',
      hail: 'storm',
      thunder: 'storm',
      thunderstorm: 'storm',
      lightning: 'storm',
      wind: 'storm',
      windy: 'storm',
      gale: 'storm',
      hurricane: 'storm',
      sunny: 'clear',
      calm: 'clear',
      none: 'clear',
    },
  },

  archetype: {
    options: archetypeSchema.options,
    aliases: {
      boss: 'leader',
      captain: 'leader',
      chief: 'leader',
      commander: 'leader',
      veteran: 'mentor',
      teacher: 'mentor',
      guide: 'mentor',
      elder: 'mentor',
      novice: 'rookie',
      newcomer: 'rookie',
      apprentice: 'rookie',
      kid: 'rookie',
      child: 'rookie',
      student: 'rookie',
      genius: 'mastermind',
      planner: 'mastermind',
      detective: 'mastermind',
      scientist: 'mastermind',
      doctor: 'mastermind',
      villain: 'rival',
      antagonist: 'rival',
      enemy: 'rival',
      nemesis: 'rival',
      opponent: 'rival',
      sentry: 'guard',
      soldier: 'guard',
      officer: 'guard',
      cop: 'guard',
      police: 'guard',
      security: 'guard',
      warden: 'guard',
      spirit: 'ghost',
      phantom: 'ghost',
      apparition: 'ghost',
      spectre: 'ghost',
      specter: 'ghost',
      wraith: 'ghost',
      outsider: 'stranger',
      drifter: 'stranger',
      wanderer: 'stranger',
      visitor: 'stranger',
      unknown: 'stranger',
      survivor: 'stranger',
      victim: 'stranger',
      witness: 'stranger',
      narrator: 'stranger',
    },
    fallback: 'stranger',
  },

  build: {
    options: buildSchema.options,
    aliases: {
      thin: 'slight',
      slim: 'slight',
      small: 'slight',
      petite: 'slight',
      lean: 'slight',
      frail: 'slight',
      wiry: 'slight',
      medium: 'average',
      normal: 'average',
      moderate: 'average',
      large: 'heavy',
      big: 'heavy',
      broad: 'heavy',
      stocky: 'heavy',
      burly: 'heavy',
      muscular: 'heavy',
      imposing: 'tall',
      lanky: 'tall',
      towering: 'tall',
    },
  },

  voiceRegister: {
    options: voiceRegisterSchema.options,
    aliases: {
      deep: 'low',
      bass: 'low',
      baritone: 'low',
      gravelly: 'low',
      middle: 'mid',
      medium: 'mid',
      tenor: 'mid',
      alto: 'mid',
      neutral: 'mid',
      soprano: 'high',
      light: 'high',
      shrill: 'high',
    },
    fallback: 'mid',
  },

  voiceRate: {
    options: voiceRateSchema.options,
    aliases: {
      slowly: 'slow',
      deliberate: 'slow',
      measured: 'slow',
      drawl: 'slow',
      moderate: 'normal',
      medium: 'normal',
      steady: 'normal',
      quick: 'fast',
      rapid: 'fast',
      hurried: 'fast',
      clipped: 'fast',
    },
    fallback: 'normal',
  },

  entranceFrom: {
    options: entranceFromSchema.options,
    aliases: {
      left: 'offLeft',
      stageleft: 'offLeft',
      fromleft: 'offLeft',
      offstage: 'offLeft',
      offscreen: 'offLeft',
      right: 'offRight',
      stageright: 'offRight',
      fromright: 'offRight',
      door: 'offRight',
      shadows: 'shadow',
      darkness: 'shadow',
      dark: 'shadow',
      behind: 'shadow',
      ceiling: 'above',
      sky: 'above',
      overhead: 'above',
      top: 'above',
      stairs: 'above',
      present: 'already-present',
      onstage: 'already-present',
      center: 'already-present',
      none: 'already-present',
      static: 'already-present',
    },
    fallback: 'offLeft',
  },

  exitTo: {
    options: exitToSchema.options,
    aliases: {
      left: 'offLeft',
      stageleft: 'offLeft',
      toleft: 'offLeft',
      offstage: 'offLeft',
      offscreen: 'offLeft',
      right: 'offRight',
      stageright: 'offRight',
      toright: 'offRight',
      door: 'offRight',
      shadows: 'shadow',
      darkness: 'shadow',
      dark: 'shadow',
      behind: 'shadow',
      ceiling: 'above',
      sky: 'above',
      overhead: 'above',
      top: 'above',
      stairs: 'above',
    },
    fallback: 'offRight',
  },

  movementStyle: {
    options: movementStyleSchema.options,
    aliases: {
      run: 'stride',
      running: 'stride',
      rush: 'stride',
      hurry: 'stride',
      march: 'stride',
      strut: 'stride',
      sneak: 'creep',
      crawl: 'creep',
      slink: 'creep',
      tiptoe: 'creep',
      slow: 'creep',
      slam: 'burst',
      charge: 'burst',
      crash: 'burst',
      explode: 'burst',
      appear: 'fade',
      materialize: 'fade',
      dissolve: 'fade',
      drift: 'fade',
      float: 'fade',
      glide: 'fade',
      emerge: 'fade',
      stand: 'walk',
      standing: 'walk',
      still: 'walk',
      static: 'walk',
      none: 'walk',
      enter: 'walk',
      step: 'walk',
      stroll: 'walk',
      amble: 'walk',
      saunter: 'walk',
      shuffle: 'walk',
      limp: 'walk',
    },
    fallback: 'walk',
  },

  travelStyle: {
    options: travelStyleSchema.options,
    aliases: {
      stride: 'walk',
      step: 'walk',
      stroll: 'walk',
      stand: 'walk',
      still: 'walk',
      none: 'walk',
      run: 'rush',
      burst: 'rush',
      hurry: 'rush',
      dash: 'rush',
      sprint: 'rush',
      charge: 'rush',
      sneak: 'creep',
      crawl: 'creep',
      tiptoe: 'creep',
      slink: 'creep',
      fade: 'drift',
      float: 'drift',
      glide: 'drift',
      slide: 'drift',
    },
    fallback: 'walk',
  },

  silhouetteAccent: {
    options: silhouetteAccentSchema.options,
    aliases: {
      cap: 'hat',
      fedora: 'hat',
      helmet: 'hat',
      hood: 'hat',
      crown: 'hat',
      jacket: 'coat',
      trench: 'coat',
      trenchcoat: 'coat',
      cloak: 'cape',
      robe: 'cape',
      shawl: 'cape',
      bag: 'briefcase',
      case: 'briefcase',
      suitcase: 'briefcase',
      satchel: 'briefcase',
      backpack: 'briefcase',
      lantern: 'briefcase',
      staff: 'cane',
      stick: 'cane',
      walkingstick: 'cane',
      umbrella: 'cane',
      nothing: 'none',
    },
  },

  cameraMove: {
    options: cameraMoveSchema.options,
    aliases: {
      zoomin: 'pushIn',
      closein: 'pushIn',
      closeup: 'pushIn',
      rackfocus: 'pushIn',
      zoomout: 'pullBack',
      pullout: 'pullBack',
      wide: 'pullBack',
      wideshot: 'pullBack',
      establishing: 'pullBack',
      pan: 'panRight',
      swishpan: 'whipPan',
      snapzoom: 'whipPan',
      tiltup: 'craneUp',
      crane: 'craneUp',
      boomup: 'craneUp',
      tilt: 'craneUp',
      aerial: 'craneUp',
      dolly: 'dollyIn',
      truckin: 'dollyIn',
      tracking: 'dollyIn',
      trackingshot: 'dollyIn',
      shake: 'handheld',
      shaky: 'handheld',
      steadicam: 'handheld',
      orbit: 'handheld',
      arc: 'handheld',
      still: 'static',
      locked: 'static',
      lockedoff: 'static',
      fixed: 'static',
      hold: 'static',
      cut: 'static',
      none: 'static',
    },
    fallback: 'static',
  },

  cameraIntensity: {
    options: cameraIntensitySchema.options,
    aliases: {
      slight: 'subtle',
      gentle: 'subtle',
      soft: 'subtle',
      slow: 'subtle',
      minimal: 'subtle',
      medium: 'normal',
      moderate: 'normal',
      standard: 'normal',
      strong: 'dramatic',
      intense: 'dramatic',
      extreme: 'dramatic',
      heavy: 'dramatic',
      aggressive: 'dramatic',
      fast: 'dramatic',
    },
    fallback: 'normal',
  },

  lightingPreset: {
    options: lightingPresetSchema.options,
    aliases: {
      warm: 'warmInterior',
      warmlight: 'warmInterior',
      lamplight: 'warmInterior',
      daylight: 'warmInterior',
      sunlight: 'warmInterior',
      golden: 'warmInterior',
      candlelight: 'firelight',
      candle: 'firelight',
      fire: 'firelight',
      torch: 'firelight',
      hearth: 'firelight',
      ember: 'firelight',
      moonlight: 'coldMoonlight',
      moon: 'coldMoonlight',
      cold: 'coldMoonlight',
      blue: 'coldMoonlight',
      starlight: 'coldMoonlight',
      spotlight: 'singleSpot',
      spot: 'singleSpot',
      singlelight: 'singleSpot',
      lamp: 'singleSpot',
      flashlight: 'singleSpot',
      dim: 'singleSpot',
      backlight: 'silhouetteBacklight',
      backlit: 'silhouetteBacklight',
      rimlight: 'silhouetteBacklight',
      silhouette: 'silhouetteBacklight',
      neon: 'neonWash',
      neonlight: 'neonWash',
      cyberpunk: 'neonWash',
      dark: 'blackout',
      black: 'blackout',
      darkness: 'blackout',
      off: 'blackout',
      none: 'blackout',
      fluorescent: 'harshFluorescent',
      harsh: 'harshFluorescent',
      sterile: 'harshFluorescent',
      clinical: 'harshFluorescent',
      overhead: 'harshFluorescent',
      lightning: 'harshFluorescent',
    },
    fallback: 'warmInterior',
  },

  lightingTransition: {
    options: lightingTransitionSchema.options,
    aliases: {
      instant: 'cut',
      hard: 'cut',
      snap: 'cut',
      immediate: 'cut',
      crossfade: 'fade',
      dissolve: 'fade',
      gradual: 'fade',
      smooth: 'fade',
      slow: 'fade',
      flickering: 'flicker',
      strobe: 'flicker',
      pulse: 'flicker',
      stutter: 'flicker',
      blink: 'flicker',
    },
    fallback: 'fade',
  },

  musicAction: {
    options: musicActionSchema.options,
    aliases: {
      begin: 'start',
      play: 'start',
      enter: 'start',
      fadein: 'start',
      build: 'swell',
      rise: 'swell',
      crescendo: 'swell',
      grow: 'swell',
      lower: 'duck',
      quiet: 'duck',
      soften: 'duck',
      under: 'duck',
      end: 'stop',
      cut: 'stop',
      fadeout: 'stop',
      silence: 'stop',
      hit: 'sting',
      accent: 'sting',
      stinger: 'sting',
      punch: 'sting',
    },
    fallback: 'start',
  },

  musicStinger: {
    options: musicStingerSchema.options,
    aliases: {
      stab: 'hit',
      impact: 'hit',
      rise: 'riser',
      swell: 'riser',
      whoosh: 'riser',
      bass: 'boom',
      thud: 'boom',
      rumble: 'boom',
      bell: 'chime',
      ding: 'chime',
      tone: 'chime',
      sustain: 'drone',
      hum: 'drone',
      pad: 'drone',
    },
  },

  particleEffect: {
    options: particleEffectSchema.options,
    aliases: {
      motes: 'dust',
      dustmotes: 'dust',
      particles: 'dust',
      leaves: 'dust',
      feathers: 'dust',
      ash: 'embers',
      ashes: 'embers',
      cinders: 'embers',
      fire: 'embers',
      sparkles: 'sparks',
      electricity: 'sparks',
      static: 'sparks',
      fog: 'smoke',
      mist: 'smoke',
      steam: 'smoke',
      haze: 'smoke',
      vapor: 'smoke',
      snowflakes: 'snow',
      drizzle: 'rain',
      downpour: 'rain',
      water: 'rain',
      nothing: 'none',
    },
    fallback: 'none',
  },

  particleAction: {
    options: particleActionSchema.options,
    aliases: {
      begin: 'start',
      on: 'start',
      enable: 'start',
      end: 'stop',
      off: 'stop',
      disable: 'stop',
      none: 'stop',
    },
    fallback: 'start',
  },

  stageSlot: {
    options: stageSlotSchema.options,
    aliases: {
      extremeleft: 'farLeft',
      leftedge: 'farLeft',
      extremeright: 'farRight',
      rightedge: 'farRight',
      stageleft: 'left',
      stageright: 'right',
      centre: 'center',
      middle: 'center',
      centerstage: 'center',
      midstage: 'center',
      downstage: 'center',
      upstage: 'center',
      foreground: 'center',
      background: 'center',
    },
    fallback: 'center',
  },

  facing: {
    options: facingSchema.options,
    aliases: {
      forward: 'front',
      camera: 'front',
      audience: 'front',
      ahead: 'front',
      out: 'front',
      centre: 'front',
      center: 'front',
      stageleft: 'left',
      toleft: 'left',
      stageright: 'right',
      toright: 'right',
    },
  },

  delivery: {
    options: deliverySchema.options,
    aliases: {
      monotone: 'flat',
      deadpan: 'flat',
      calm: 'flat',
      neutral: 'flat',
      cold: 'flat',
      even: 'flat',
      quiet: 'whisper',
      whispered: 'whisper',
      hushed: 'whisper',
      soft: 'whisper',
      murmur: 'whisper',
      low: 'whisper',
      yell: 'shout',
      yelling: 'shout',
      scream: 'shout',
      screaming: 'shout',
      loud: 'shout',
      angry: 'shout',
      shouted: 'shout',
      urgently: 'urgent',
      hurried: 'urgent',
      frantic: 'urgent',
      breathless: 'urgent',
      tense: 'urgent',
      sarcastic: 'wry',
      ironic: 'wry',
      amused: 'wry',
      dry: 'wry',
      sardonic: 'wry',
      wryly: 'wry',
      shaky: 'trembling',
      shaking: 'trembling',
      scared: 'trembling',
      afraid: 'trembling',
      tearful: 'trembling',
      fearful: 'trembling',
      nervous: 'trembling',
      terrified: 'trembling',
    },
  },

  gesture: {
    options: gestureSchema.options,
    aliases: {
      pointing: 'point',
      points: 'point',
      indicate: 'point',
      shrugs: 'shrug',
      shrugging: 'shrug',
      stepsforward: 'step-forward',
      advance: 'step-forward',
      approach: 'step-forward',
      lean: 'step-forward',
      flinch: 'recoil',
      recoils: 'recoil',
      stepback: 'recoil',
      backaway: 'recoil',
      startle: 'recoil',
      nods: 'nod',
      nodding: 'nod',
      agree: 'nod',
      bow: 'nod',
      reaches: 'reach',
      reaching: 'reach',
      grab: 'reach',
      extend: 'reach',
      offer: 'reach',
      turnsaway: 'turn-away',
      turn: 'turn-away',
      lookaway: 'turn-away',
      avert: 'turn-away',
      nothing: 'none',
      still: 'none',
    },
    fallback: 'none',
  },

  outroStyle: {
    options: outroStyleSchema.options,
    aliases: {
      cut: 'cutToBlack',
      black: 'cutToBlack',
      hardcut: 'cutToBlack',
      title: 'titleSlam',
      titlecard: 'titleSlam',
      slam: 'titleSlam',
      fade: 'fadeOut',
      fadetoblack: 'fadeOut',
      dissolve: 'fadeOut',
      hold: 'holdOnActor',
      freeze: 'holdOnActor',
      freezeframe: 'holdOnActor',
      linger: 'holdOnActor',
    },
    fallback: 'fadeOut',
  },

  /**
   * No fallback by design: a beat whose type can't be recognized has no
   * renderable content to guess at, so it must fail validation and let the
   * retry/seed-fallback chain handle it rather than silently becoming a
   * different kind of beat.
   */
  beatType: {
    options: beatTypeOptions,
    aliases: {
      dialog: 'dialogue',
      speech: 'dialogue',
      line: 'dialogue',
      speak: 'dialogue',
      pause: 'beat',
      silence: 'beat',
      hold: 'beat',
      wait: 'beat',
      music: 'beat',
      sound: 'beat',
      sfx: 'beat',
      ambient: 'beat',
      transition: 'beat',
      titlecard: 'title',
      maintitle: 'title',
      location: 'slugline',
      establishing: 'slugline',
      header: 'slugline',
      description: 'action',
      narration: 'action',
      actionline: 'action',
      twist: 'reveal',
      revelation: 'reveal',
      sting: 'reveal',
      shock: 'reveal',
    },
  },
} as const satisfies Record<string, Vocabulary<string>>

/**
 * Guards against an alias key that isn't in canonical form, which would be
 * dead weight the matcher could never hit. Exercised by the unit tests
 * rather than at runtime.
 */
export function findNonCanonicalAliasKeys(): string[] {
  const offenders: string[] = []
  for (const [name, vocabulary] of Object.entries(vocabularies)) {
    for (const key of Object.keys(vocabulary.aliases)) {
      if (canonicalToken(key) !== key) offenders.push(`${name}.${key}`)
    }
  }
  return offenders
}

/**
 * Guards against an alias whose target isn't a member of its own
 * vocabulary — which would coerce a value straight into a second Zod
 * failure. Exercised by the unit tests.
 */
export function findUnresolvableAliasTargets(): string[] {
  const offenders: string[] = []
  for (const [name, vocabulary] of Object.entries(vocabularies)) {
    const options = vocabulary.options as readonly string[]
    for (const [key, target] of Object.entries(vocabulary.aliases)) {
      if (!options.includes(target)) offenders.push(`${name}.${key} -> ${target}`)
    }
    const fallback = (vocabulary as Vocabulary<string>).fallback
    if (fallback !== undefined && !options.includes(fallback)) {
      offenders.push(`${name}.fallback -> ${fallback}`)
    }
  }
  return offenders
}
